var tzlist = [
  {"id":"Pacific/Midway","value":"(UTC-11:00) Midway Island","place":"Midway Island","time":"-11:00"},
  {"id":"Pacific/Samoa","value":"(UTC-11:00) Samoa","place":"Samoa","time":"-11:00"},
  {"id":"Pacific/Honolulu","value":"(UTC-10:00) Hawaii","place":"Hawaii","time":"-10:00"},
  {"id":"US/Alaska","value":"(UTC-09:00) Alaska","place":"Alaska","time":"-09:00"},
  {"id":"America/Los_Angeles","value":"(UTC-08:00) Pacific Time (US & Canada)","place":"Pacific Time (US & Canada)","time":"-08:00"},
  {"id":"America/Tijuana","value":"(UTC-08:00) Tijuana","place":"Tijuana","time":"-08:00"},
  {"id":"US/Arizona","value":"(UTC-07:00) Arizona","place":"Arizona","time":"-07:00"},
  {"id":"America/Chihuahua","value":"(UTC-07:00) Chihuahua","place":"Chihuahua","time":"-07:00"},
  {"id":"America/Chihuahua","value":"(UTC-07:00) La Paz","place":"La Paz","time":"-07:00"},
  {"id":"America/Mazatlan","value":"(UTC-07:00) Mazatlan","place":"Mazatlan","time":"-07:00"},
  {"id":"US/Mountain","value":"(UTC-07:00) Mountain Time (US & Canada)","place":"Mountain Time (US & Canada)","time":"-07:00"},
  {"id":"America/Managua","value":"(UTC-06:00) Central America","place":"Central America","time":"-06:00"},
  {"id":"US/Central","value":"(UTC-06:00) Central Time (US & Canada)","place":"Central Time (US & Canada)","time":"-06:00"},
  {"id":"America/Mexico_City","value":"(UTC-06:00) Guadalajara","place":"Guadalajara","time":"-06:00"},
  {"id":"America/Mexico_City","value":"(UTC-06:00) Mexico City","place":"Mexico City","time":"-06:00"},
  {"id":"America/Monterrey","value":"(UTC-06:00) Monterrey","place":"Monterrey","time":"-06:00"},
  {"id":"Canada/Saskatchewan","value":"(UTC-06:00) Saskatchewan","place":"Saskatchewan","time":"-06:00"},
  {"id":"America/Bogota","value":"(UTC-05:00) Bogota","place":"Bogota","time":"-05:00"},
  {"id":"US/Eastern","value":"(UTC-05:00) Eastern Time (US & Canada)","place":"Eastern Time (US & Canada)","time":"-05:00"},
  {"id":"US/East-Indiana","value":"(UTC-05:00) Indiana (East)","place":"Indiana (East)","time":"-05:00"},
  {"id":"America/Lima","value":"(UTC-05:00) Lima","place":"Lima","time":"-05:00"},
  {"id":"America/Bogota","value":"(UTC-05:00) Quito","place":"Quito","time":"-05:00"},
  {"id":"Canada/Atlantic","value":"(UTC-04:00) Atlantic Time (Canada)","place":"Atlantic Time (Canada)","time":"-04:00"},
  {"id":"America/Caracas","value":"(UTC-04:30) Caracas","place":"Caracas","time":"-04:30"},
  {"id":"America/La_Paz","value":"(UTC-04:00) La Paz","place":"La Paz","time":"-04:00"},
  {"id":"America/Santiago","value":"(UTC-04:00) Santiago","place":"Santiago","time":"-04:00"},
  {"id":"Canada/Newfoundland","value":"(UTC-03:30) Newfoundland","place":"Newfoundland","time":"-03:30"},
  {"id":"America/Sao_Paulo","value":"(UTC-03:00) Brasilia","place":"Brasilia","time":"-03:00"},
  {"id":"America/Argentina/Buenos_Aires","value":"(UTC-03:00) Buenos Aires","place":"Buenos Aires","time":"-03:00"},
  {"id":"America/Argentina/Buenos_Aires","value":"(UTC-03:00) Georgetown","place":"Georgetown","time":"-03:00"},
  {"id":"America/Godthab","value":"(UTC-03:00) Greenland","place":"Greenland","time":"-03:00"},
  {"id":"America/Noronha","value":"(UTC-02:00) Mid-Atlantic","place":"Mid-Atlantic","time":"-02:00"},
  {"id":"Atlantic/Azores","value":"(UTC-01:00) Azores","place":"Azores","time":"-01:00"},
  {"id":"Atlantic/Cape_Verde","value":"(UTC-01:00) Cape Verde Is.","place":"Cape Verde Is.","time":"-01:00"},
  {"id":"Africa/Casablanca","value":"(UTC+00:00) Casablanca","place":"Casablanca","time":"+00:00"},
  {"id":"Europe/London","value":"(UTC+00:00) Edinburgh","place":"Edinburgh","time":"+00:00"},
  {"id":"Etc/Greenwich","value":"(UTC+00:00) Greenwich Mean Time : Dublin","place":"Greenwich Mean Time : Dublin","time":"+00:00"},
  {"id":"Europe/Lisbon","value":"(UTC+00:00) Lisbon","place":"Lisbon","time":"+00:00"},
  {"id":"Europe/London","value":"(UTC+00:00) London","place":"London","time":"+00:00"},
  {"id":"Africa/Monrovia","value":"(UTC+00:00) Monrovia","place":"Monrovia","time":"+00:00"},
  {"id":"UTC","value":"(UTC+00:00) UTC","place":"UTC","time":"+00:00"},
  {"id":"Europe/Amsterdam","value":"(UTC+01:00) Amsterdam","place":"Amsterdam","time":"+01:00"},
  {"id":"Europe/Belgrade","value":"(UTC+01:00) Belgrade","place":"Belgrade","time":"+01:00"},
  {"id":"Europe/Berlin","value":"(UTC+01:00) Berlin","place":"Berlin","time":"+01:00"},
  {"id":"Europe/Berlin","value":"(UTC+01:00) Bern","place":"Bern","time":"+01:00"},
  {"id":"Europe/Bratislava","value":"(UTC+01:00) Bratislava","place":"Bratislava","time":"+01:00"},
  {"id":"Europe/Brussels","value":"(UTC+01:00) Brussels","place":"Brussels","time":"+01:00"},
  {"id":"Europe/Budapest","value":"(UTC+01:00) Budapest","place":"Budapest","time":"+01:00"},
  {"id":"Europe/Copenhagen","value":"(UTC+01:00) Copenhagen","place":"Copenhagen","time":"+01:00"},
  {"id":"Europe/Ljubljana","value":"(UTC+01:00) Ljubljana","place":"Ljubljana","time":"+01:00"},
  {"id":"Europe/Madrid","value":"(UTC+01:00) Madrid","place":"Madrid","time":"+01:00"},
  {"id":"Europe/Paris","value":"(UTC+01:00) Paris","place":"Paris","time":"+01:00"},
  {"id":"Europe/Prague","value":"(UTC+01:00) Prague","place":"Prague","time":"+01:00"},
  {"id":"Europe/Rome","value":"(UTC+01:00) Rome","place":"Rome","time":"+01:00"},
  {"id":"Europe/Sarajevo","value":"(UTC+01:00) Sarajevo","place":"Sarajevo","time":"+01:00"},
  {"id":"Europe/Skopje","value":"(UTC+01:00) Skopje","place":"Skopje","time":"+01:00"},
  {"id":"Europe/Stockholm","value":"(UTC+01:00) Stockholm","place":"Stockholm","time":"+01:00"},
  {"id":"Europe/Vienna","value":"(UTC+01:00) Vienna","place":"Vienna","time":"+01:00"},
  {"id":"Europe/Warsaw","value":"(UTC+01:00) Warsaw","place":"Warsaw","time":"+01:00"},
  {"id":"Africa/Lagos","value":"(UTC+01:00) West Central Africa","place":"West Central Africa","time":"+01:00"},
  {"id":"Europe/Zagreb","value":"(UTC+01:00) Zagreb","place":"Zagreb","time":"+01:00"},
  {"id":"Europe/Athens","value":"(UTC+02:00) Athens","place":"Athens","time":"+02:00"},
  {"id":"Europe/Bucharest","value":"(UTC+02:00) Bucharest","place":"Bucharest","time":"+02:00"},
  {"id":"Africa/Cairo","value":"(UTC+02:00) Cairo","place":"Cairo","time":"+02:00"},
  {"id":"Africa/Harare","value":"(UTC+02:00) Harare","place":"Harare","time":"+02:00"},
  {"id":"Europe/Helsinki","value":"(UTC+02:00) Helsinki","place":"Helsinki","time":"+02:00"},
  {"id":"Europe/Istanbul","value":"(UTC+02:00) Istanbul","place":"Istanbul","time":"+02:00"},
  {"id":"Asia/Jerusalem","value":"(UTC+02:00) Jerusalem","place":"Jerusalem","time":"+02:00"},
  {"id":"Europe/Helsinki","value":"(UTC+02:00) Kyiv","place":"Kyiv","time":"+02:00"},
  {"id":"Africa/Johannesburg","value":"(UTC+02:00) Pretoria","place":"Pretoria","time":"+02:00"},
  {"id":"Europe/Riga","value":"(UTC+02:00) Riga","place":"Riga","time":"+02:00"},
  {"id":"Europe/Sofia","value":"(UTC+02:00) Sofia","place":"Sofia","time":"+02:00"},
  {"id":"Europe/Tallinn","value":"(UTC+02:00) Tallinn","place":"Tallinn","time":"+02:00"},
  {"id":"Europe/Vilnius","value":"(UTC+02:00) Vilnius","place":"Vilnius","time":"+02:00"},
  {"id":"Asia/Baghdad","value":"(UTC+03:00) Baghdad","place":"Baghdad","time":"+03:00"},
  {"id":"Asia/Kuwait","value":"(UTC+03:00) Kuwait","place":"Kuwait","time":"+03:00"},
  {"id":"Europe/Minsk","value":"(UTC+03:00) Minsk","place":"Minsk","time":"+03:00"},
  {"id":"Africa/Nairobi","value":"(UTC+03:00) Nairobi","place":"Nairobi","time":"+03:00"},
  {"id":"Asia/Riyadh","value":"(UTC+03:00) Riyadh","place":"Riyadh","time":"+03:00"},
  {"id":"Europe/Volgograd","value":"(UTC+03:00) Volgograd","place":"Volgograd","time":"+03:00"},
  {"id":"Asia/Tehran","value":"(UTC+03:30) Tehran","place":"Tehran","time":"+03:30"},
  {"id":"Asia/Muscat","value":"(UTC+04:00) Abu Dhabi","place":"Abu Dhabi","time":"+04:00"},
  {"id":"Asia/Baku","value":"(UTC+04:00) Baku","place":"Baku","time":"+04:00"},
  {"id":"Europe/Moscow","value":"(UTC+04:00) Moscow","place":"Moscow","time":"+04:00"},
  {"id":"Asia/Muscat","value":"(UTC+04:00) Muscat","place":"Muscat","time":"+04:00"},
  {"id":"Europe/Moscow","value":"(UTC+04:00) St. Petersburg","place":"St. Petersburg","time":"+04:00"},
  {"id":"Asia/Tbilisi","value":"(UTC+04:00) Tbilisi","place":"Tbilisi","time":"+04:00"},
  {"id":"Asia/Yerevan","value":"(UTC+04:00) Yerevan","place":"Yerevan","time":"+04:00"},
  {"id":"Asia/Kabul","value":"(UTC+04:30) Kabul","place":"Kabul","time":"+04:30"},
  {"id":"Asia/Karachi","value":"(UTC+05:00) Islamabad","place":"Islamabad","time":"+05:00"},
  {"id":"Asia/Karachi","value":"(UTC+05:00) Karachi","place":"Karachi","time":"+05:00"},
  {"id":"Asia/Tashkent","value":"(UTC+05:00) Tashkent","place":"Tashkent","time":"+05:00"},
  {"id":"Asia/Calcutta","value":"(UTC+05:30) Chennai","place":"Chennai","time":"+05:30"},
  {"id":"Asia/Kolkata","value":"(UTC+05:30) Kolkata","place":"Kolkata","time":"+05:30"},
  {"id":"Asia/Calcutta","value":"(UTC+05:30) Mumbai","place":"Mumbai","time":"+05:30"},
  {"id":"Asia/Calcutta","value":"(UTC+05:30) New Delhi","place":"New Delhi","time":"+05:30"},
  {"id":"Asia/Calcutta","value":"(UTC+05:30) Sri Jayawardenepura","place":"Sri Jayawardenepura","time":"+05:30"},
  {"id":"Asia/Katmandu","value":"(UTC+05:45) Kathmandu","place":"Kathmandu","time":"+05:45"},
  {"id":"Asia/Almaty","value":"(UTC+06:00) Almaty","place":"Almaty","time":"+06:00"},
  {"id":"Asia/Dhaka","value":"(UTC+06:00) Astana","place":"Astana","time":"+06:00"},
  {"id":"Asia/Dhaka","value":"(UTC+06:00) Dhaka","place":"Dhaka","time":"+06:00"},
  {"id":"Asia/Yekaterinburg","value":"(UTC+06:00) Ekaterinburg","place":"Ekaterinburg","time":"+06:00"},
  {"id":"Asia/Rangoon","value":"(UTC+06:30) Rangoon","place":"Rangoon","time":"+06:30"},
  {"id":"Asia/Bangkok","value":"(UTC+07:00) Bangkok","place":"Bangkok","time":"+07:00"},
  {"id":"Asia/Bangkok","value":"(UTC+07:00) Hanoi","place":"Hanoi","time":"+07:00"},
  {"id":"Asia/Jakarta","value":"(UTC+07:00) Jakarta","place":"Jakarta","time":"+07:00"},
  {"id":"Asia/Novosibirsk","value":"(UTC+07:00) Novosibirsk","place":"Novosibirsk","time":"+07:00"},
  {"id":"Asia/Hong_Kong","value":"(UTC+08:00) Beijing","place":"Beijing","time":"+08:00"},
  {"id":"Asia/Chongqing","value":"(UTC+08:00) Chongqing","place":"Chongqing","time":"+08:00"},
  {"id":"Asia/Hong_Kong","value":"(UTC+08:00) Hong Kong","place":"Hong Kong","time":"+08:00"},
  {"id":"Asia/Krasnoyarsk","value":"(UTC+08:00) Krasnoyarsk","place":"Krasnoyarsk","time":"+08:00"},
  {"id":"Asia/Kuala_Lumpur","value":"(UTC+08:00) Kuala Lumpur","place":"Kuala Lumpur","time":"+08:00"},
  {"id":"Australia/Perth","value":"(UTC+08:00) Perth","place":"Perth","time":"+08:00"},
  {"id":"Asia/Singapore","value":"(UTC+08:00) Singapore","place":"Singapore","time":"+08:00"},
  {"id":"Asia/Taipei","value":"(UTC+08:00) Taipei","place":"Taipei","time":"+08:00"},
  {"id":"Asia/Ulan_Bator","value":"(UTC+08:00) Ulaan Bataar","place":"Ulaan Bataar","time":"+08:00"},
  {"id":"Asia/Urumqi","value":"(UTC+08:00) Urumqi","place":"Urumqi","time":"+08:00"},
  {"id":"Asia/Irkutsk","value":"(UTC+09:00) Irkutsk","place":"Irkutsk","time":"+09:00"},
  {"id":"Asia/Tokyo","value":"(UTC+09:00) Osaka","place":"Osaka","time":"+09:00"},
  {"id":"Asia/Tokyo","value":"(UTC+09:00) Sapporo","place":"Sapporo","time":"+09:00"},
  {"id":"Asia/Seoul","value":"(UTC+09:00) Seoul","place":"Seoul","time":"+09:00"},
  {"id":"Asia/Tokyo","value":"(UTC+09:00) Tokyo","place":"Tokyo","time":"+09:00"},
  {"id":"Australia/Adelaide","value":"(UTC+09:30) Adelaide","place":"Adelaide","time":"+09:30"},
  {"id":"Australia/Darwin","value":"(UTC+09:30) Darwin","place":"Darwin","time":"+09:30"},
  {"id":"Australia/Brisbane","value":"(UTC+10:00) Brisbane","place":"Brisbane","time":"+10:00"},
  {"id":"Australia/Canberra","value":"(UTC+10:00) Canberra","place":"Canberra","time":"+10:00"},
  {"id":"Pacific/Guam","value":"(UTC+10:00) Guam","place":"Guam","time":"+10:00"},
  {"id":"Australia/Hobart","value":"(UTC+10:00) Hobart","place":"Hobart","time":"+10:00"},
  {"id":"Australia/Melbourne","value":"(UTC+10:00) Melbourne","place":"Melbourne","time":"+10:00"},
  {"id":"Pacific/Port_Moresby","value":"(UTC+10:00) Port Moresby","place":"Port Moresby","time":"+10:00"},
  {"id":"Australia/Sydney","value":"(UTC+10:00) Sydney","place":"Sydney","time":"+10:00"},
  {"id":"Asia/Yakutsk","value":"(UTC+10:00) Yakutsk","place":"Yakutsk","time":"+10:00"},
  {"id":"Asia/Vladivostok","value":"(UTC+11:00) Vladivostok","place":"Vladivostok","time":"+11:00"},
  {"id":"Pacific/Auckland","value":"(UTC+12:00) Auckland","place":"Auckland","time":"+12:00"},
  {"id":"Pacific/Fiji","value":"(UTC+12:00) Fiji","place":"Fiji","time":"+12:00"},
  {"id":"Pacific/Kwajalein","value":"(UTC+12:00) International Date Line West","place":"International Date Line West","time":"+12:00"},
  {"id":"Asia/Kamchatka","value":"(UTC+12:00) Kamchatka","place":"Kamchatka","time":"+12:00"},
  {"id":"Asia/Magadan","value":"(UTC+12:00) Magadan","place":"Magadan","time":"+12:00"},
  {"id":"Pacific/Fiji","value":"(UTC+12:00) Marshall Is.","place":"Marshall Is.","time":"+12:00"},
  {"id":"Asia/Magadan","value":"(UTC+12:00) New Caledonia","place":"New Caledonia","time":"+12:00"},
  {"id":"Asia/Magadan","value":"(UTC+12:00) Solomon Is.","place":"Solomon Is.","time":"+12:00"},
  {"id":"Pacific/Auckland","value":"(UTC+12:00) Wellington","place":"Wellington","time":"+12:00"},
  {"id":"Pacific/Tongatapu","value":"(UTC+13:00) Nuku'alofa","place":"Nuku'alofa","time":"+13:00"}
]

module.exports = tzlist
